spring:
  datasource:
    url: jdbc:h2:mem:clips;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
logging:
  level:
    com.example.youtube: DEBUG
